title: LibreELEC
email:
description: Just enough OS for KODI
author: LibreELEC
baseurl: ""
url: "https://libreelec.tv"
default_header_logo: "img/bg-index.jpg" # relative path to default header logo

# Social Profiles
twitter_username: LibreELEC
github_username: LibreELEC/LibreELEC.tv
facebook_username:
instagram_username:
linkedin_username:
reddit_url: https://www.reddit.com/r/LibreELEC
youtube_url: https://www.youtube.com/channel/UC7FSO0rXOtO6w_poBLvvjDw
wiki_url: https://libreelec.wiki

# Add your google-analytics ID here to activate google analytics
google_analytics: # out your google-analytics code

# LE
post_limit: 5 # number of posts shown
post_subtitle_limit: 40 # number of words included at post preview

# Build settings
markdown: kramdown
paginate: 6
paginate_path: "/posts/page/:num/"
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# LE downloads

# download url
le_download_url: https://releases.libreelec.tv

# LE12.0
release_date_le_12_0: 2024.03
kodi_version_le_12_0: 21.0
le_version_download_12_0: 11.95.1
le_version_name_12_0: 12.0
kernel_version_le_12_0: 6.6.x

# LE11.0
release_date_le_11_0: 2024.01
kodi_version_le_11_0: 20.3
le_version_download_11_0: 11.0.6
le_version_name_11_0: 11.0
kernel_version_le_11_0: 6.1.x

# LE10.0
release_date_le_10_0: 2023.01
kodi_version_le_10_0: 19.5
le_version_download_10_0: 10.0.4
le_version_name_10_0: 10.0
kernel_version_le_10_0: 5.10.x

# LE9.2
release_date_le_9_2: 2020.11
kodi_version_le_9_2: 18.9
le_version_download_9_2: 9.2.6
le_version_download_rpi_9_2: 9.2.8
le_version_name_9_2: 9.2
kernel_version_le_9_2: 5.1.x
kernel_version_le_rpi_9_2: 4.19.x
kernel_version_le_rk_9_2: 4.4.x

# LE9.0 Amlogic
release_date_le_9_0: 2020.05
kodi_version_le_9_0: 18.2
le_version_download_9_0: 9.0.2
le_version_name_9_0: 9.0
kernel_version_le_9_0: 4.19.x
kernel_version_le_aml_9_0: "3.14/3.10"
